# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(System.DefaultWorkingDirectory)\source\SpecFlow\**\*.csproj'

- powershell: 'dotnet-project-licenses -i ''$(System.DefaultWorkingDirectory)\source\SpecFlow\Sopheon Cloud Specflow Build.sln'' --allowed-license-types ''$(System.DefaultWorkingDirectory)\source\SpecFlow\AllowedLicenses.json'' --output --outfile ''$(Build.ArtifactStagingDirectory)\licenses.txt'''
  displayName: 'PowerShell Script'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(System.DefaultWorkingDirectory)\source\SpecFlow\Sopheon Cloud Specflow Build.sln'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

