# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(rev:rrr)

pool: Default

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(System.DefaultWorkingDirectory)\source\SpecFlow\**\*.csproj'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet-project-licenses -i ''$(System.DefaultWorkingDirectory)\source\SpecFlow\Sopheon Cloud Specflow Build.sln'' --allowed-license-types ''$(System.DefaultWorkingDirectory)\source\SpecFlow\AllowedLicenses.json'' --output --outfile ''$(Build.ArtifactStagingDirectory)\licenses.txt'''

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(System.DefaultWorkingDirectory)\source\SpecFlow\Sopheon Cloud Specflow Build.sln'
    arguments: '-o $(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
