# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(rev:rrr)

pool: Default

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    workingDirectory: 'source\SpecFlow'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet-project-licenses -i ''source\SpecFlow'' --allowed-license-types ''source\SpecFlow\AllowedLicenses.json'' --output --outfile ''$(Build.ArtifactStagingDirectory)\licenses.txt'''

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    workingDirectory: 'source\SpecFlow'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
