// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sopheon.CloudNative.Environments.Data;

namespace Sopheon.CloudNative.Environments.Data.Migrations
{
    [DbContext(typeof(EnvironmentContext))]
    [Migration("20210923174223_AddEntities")]
    partial class AddEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ENV")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.BusinessService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BusinessServiceId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BusinessServices");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.BusinessServiceDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BusinessServiceDependencyId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessServiceId")
                        .HasColumnType("int");

                    b.Property<string>("DependencyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("BusinessServiceId", "DependencyName")
                        .IsUnique();

                    b.ToTable("BusinessServiceDependencies");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnvironmentId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("EnvironmentKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("Owner")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentKey")
                        .IsUnique();

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.EnvironmentResourceBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnvironmentResourceBindingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessServiceDependencyId")
                        .HasColumnType("int");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessServiceDependencyId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("EnvironmentId", "BusinessServiceDependencyId")
                        .IsUnique();

                    b.ToTable("EnvironmentResourceBindings");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResourceId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResourceTypeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("DomainResourceTypes");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.BusinessServiceDependency", b =>
                {
                    b.HasOne("Sopheon.CloudNative.Environments.Domain.Models.BusinessService", "BusinessService")
                        .WithMany("BusinessServiceDependencies")
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sopheon.CloudNative.Environments.Domain.Models.ResourceType", "ResourceType")
                        .WithMany("BusinessServiceDependencies")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessService");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.EnvironmentResourceBinding", b =>
                {
                    b.HasOne("Sopheon.CloudNative.Environments.Domain.Models.BusinessServiceDependency", "BusinessServiceDependency")
                        .WithMany("EnvironmentResourceBindings")
                        .HasForeignKey("BusinessServiceDependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sopheon.CloudNative.Environments.Domain.Models.Environment", "Environment")
                        .WithMany("EnvironmentResourceBindings")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sopheon.CloudNative.Environments.Domain.Models.Resource", "Resource")
                        .WithMany("EnvironmentResourceBindings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessServiceDependency");

                    b.Navigation("Environment");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.Resource", b =>
                {
                    b.HasOne("Sopheon.CloudNative.Environments.Domain.Models.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.BusinessService", b =>
                {
                    b.Navigation("BusinessServiceDependencies");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.BusinessServiceDependency", b =>
                {
                    b.Navigation("EnvironmentResourceBindings");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.Environment", b =>
                {
                    b.Navigation("EnvironmentResourceBindings");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.Resource", b =>
                {
                    b.Navigation("EnvironmentResourceBindings");
                });

            modelBuilder.Entity("Sopheon.CloudNative.Environments.Domain.Models.ResourceType", b =>
                {
                    b.Navigation("BusinessServiceDependencies");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
